circuit_classes:
  register: RegisterQC
ibm_account_names: ['ibm_cloud_free', 'ibm_quantum']
ibm_qpus:
  ibm_torino:
    basis_gates: ['cz', 'rzz', 'id', 'rx', 'rz', 'sx', 'x']
    type: heron_r1
    fake_class: FakeTorino
    fractional_gates: true
backend_classes:
  ideal: IdealAerSimulator
  aersim: AerSimFromBackend
  fakeprov: FakeProvider
  ibmqpu: IbmQpu
transpiler: # https://docs.quantum.ibm.com/guides/defaults-and-configuration-options
  seed: 457
  optimization_levels: [0, 1, 2, 3]
  approximation_degrees: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
sampler:
  dynamical_decoupling: # https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/options-dynamical-decoupling-options
    sequence_types: ['XpXm', 'XX', 'XY4']
    extra_slack_distributions: ['middle', 'ages']
    scheduling_methods: ['alap', 'asap']
  pauli_twirling: # https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/options-twirling-options
    strategies: ['active', 'active-accum', 'active-circuit', 'all']
sampler_classes:
  aer_sampler: AerSampler
  ibm_sampler: IBMRuntimeSampler